### ISSUE TITLE
There is a call error on page 184 of this book.

### ISSUE THREAD

**Issue by xiaomiwujiecao** [XadillaX/nyaa-nodejs-demo#3]
There is a call error on page 184 of this book.

```
util.inherit is not a function 
```
it should be fine just like this : 

```
util.inherits(Dog,Pet)
```
 it works in nodejs V8.12.0

**Comment by XadillaX** [comment]
Yes, you're right. Thx.
